name: upload soro-s docker image
description: 'uploads soro-s docker image to github container registry'

inputs:
  github_token:
    description: 'secrets github token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: download artifacts
      uses: actions/download-artifact@v3

    - name: docker setup-buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: docker login to github container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: docker meta data
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=edge

    - name: docker build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64

