name: 'Build SORO-S'
description: 'Builds SORO-S for Linux'
inputs:
  preset:
    description: 'CMake preset to use'
    required: true
runs:
  steps:
    - uses: actions/checkout@v3

    # ==== CMAKE ====
    - name: Generate CMake
      run: cmake --preset=${{ matrix.config.preset }}

    # ==== BUILD ====
    - name: Build soro-test
      run: |
        buildcache -z
        cmake --build build/${{ matrix.config.preset }} --target soro-test
        buildcache -s

    # ==== WEB BUILD ====
    - name: Build soro-server
      run: |
        buildcache -z
        cmake --build build/${{ matrix.config.preset }} --target soro-server
        buildcache -s