name: 'setup'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      runs-on: ubuntu-22.04
      steps:
        - name: nothing to see here
          run: |
            echo "only setting up environment variables"