name: setting up environment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  setup:
    outputs:
      runs-on: ubuntu-22.04
      steps:
        - name: empty
          run: echo ""